export type GridSpan = "1x1" | "2x1" | "1x2" | "2x2" | "4x2";

export interface ComponentItem {
  id: string;
  title: string;
  description: string;
  category: "Buttons" | "Inputs" | "Accordion" | "Feedback" | "Data" | "Navigation" | "Media" | "Typography" | "Motion" | "Layout" | "Utilities";
  span: GridSpan;
  status: "live" | "planned";
  tags: string[];
  docPath: string;
}

export const COMPONENTS_REGISTRY: ComponentItem[] = [
  {
    id: "bouncy-accordion",
    title: "Bouncy Accordion",
    description: "Smooth spring-animated accordion with audio feedback and customizable physics.",
    category: "Accordion",
    span: "2x2",
    status: "live",
    tags: ["Accordion", "Spring Motion", "Audio", "Interactive"],
    docPath: "docs/BOUNCY_ACCORDION.md",
  },
  {
    id: "metrics-card",
    title: "Metrics Card",
    description: "Data visualization card featuring smooth radial gauge progress and metrics display.",
    category: "Data",
    span: "4x2",
    status: "live",
    tags: ["Radial Gauge", "Dashboard", "Metrics", "Chart"],
    docPath: "docs/METRICS_CARD.md",
  },
  {
    id: "custom-video-player",
    title: "Custom Video Player",
    description: "Feature-rich customizable video player with fluid controls, timeline scrubber, and volume slider.",
    category: "Media",
    span: "4x2",
    status: "live",
    tags: ["Video", "Player", "Media Controls", "Full Width"],
    docPath: "docs/CUSTOM_VIDEO_PLAYER.md",
  },
  {
    id: "action-swap-button",
    title: "Action Swap Button",
    description: "CTA button and slot primitives for swapping text and icons with blur & cascade motion.",
    category: "Buttons",
    span: "2x1",
    status: "live",
    tags: ["CTA", "Cascade", "Blur", "Button"],
    docPath: "docs/ACTION_SWAP_BUTTON.md",
  },
  {
    id: "animated-badge",
    title: "Animated Badge",
    description: "Pill badge with pulsing status indicators and shimmer glow effects.",
    category: "Feedback",
    span: "1x1",
    status: "live",
    tags: ["Badge", "Pill", "Status", "Glow"],
    docPath: "docs/ANIMATED_BADGE.md",
  },
  {
    id: "animated-toast-stack",
    title: "Animated Toast Stack",
    description: "Stacked toast notifications with spring entrance, dismiss gestures, and auto-queue.",
    category: "Feedback",
    span: "2x1",
    status: "live",
    tags: ["Toast", "Notifications", "Stack", "Queue"],
    docPath: "docs/ANIMTED_TOAST_STACK.md",
  },
  {
    id: "availability-schedule",
    title: "Availability Schedule",
    description: "Interactive calendar time slot picker with animated hover highlights.",
    category: "Data",
    span: "2x2",
    status: "live",
    tags: ["Schedule", "Calendar", "Time Slots", "Picker"],
    docPath: "docs/AVAILABILITY_SCHEDULE.md",
  },
  {
    id: "buttons",
    title: "Buttons Collection",
    description: "Versatile set of interactive buttons with ripple, scale, and gradient effects.",
    category: "Buttons",
    span: "2x1",
    status: "live",
    tags: ["Buttons", "Variants", "Interactive", "Micro-animations"],
    docPath: "docs/BUTTONS.md",
  },
  {
    id: "check-box",
    title: "Animated Check Box",
    description: "Custom checkbox with smooth SVG path drawing animation and bouncy feedback.",
    category: "Inputs",
    span: "1x1",
    status: "live",
    tags: ["Checkbox", "Form", "SVG Path", "Input"],
    docPath: "docs/CHECK_BOX.md",
  },
  {
    id: "combobox-search",
    title: "Combobox Search",
    description: "Searchable dropdown autocomplete with instant filtering and active item highlight.",
    category: "Inputs",
    span: "2x1",
    status: "live",
    tags: ["Autocomplete", "Combobox", "Search", "Select"],
    docPath: "docs/COMBOBOX_SEARCH.md",
  },
  {
    id: "command-palette",
    title: "Command Palette",
    description: "Keyboard-driven spotlight command dialog with shortcut actions and fuzzy search.",
    category: "Navigation",
    span: "2x2",
    status: "live",
    tags: ["Command K", "Spotlight", "Dialog", "Search"],
    docPath: "docs/COMMAND_PALLETE.md",
  },
  {
    id: "drawer-left-right",
    title: "Drawer Left / Right",
    description: "Sliding overlay side drawers with smooth backdrop blur and drag dismissal.",
    category: "Navigation",
    span: "2x1",
    status: "live",
    tags: ["Drawer", "Slide Over", "Sidebar", "Sheet"],
    docPath: "docs/DRAWER_LEFT_RIGHT.md",
  },
  {
    id: "file-upload",
    title: "Drag & Drop File Upload",
    description: "Interactive dropzones with light & dark mode support, attachment workspace, and progress queue.",
    category: "Inputs",
    span: "4x2",
    status: "live",
    tags: ["Dropzone", "Upload", "File", "Progress", "Attachment", "Dark Mode"],
    docPath: "docs/FILE_UPLOAD.md",
  },
  {
    id: "loaders",
    title: "Motion Loaders",
    description: "Collection of minimal animated loading spinners, bouncing dots, and progress rings.",
    category: "Feedback",
    span: "2x2",
    status: "live",
    tags: ["Loader", "Spinner", "Dots", "Progress"],
    docPath: "docs/LOADERS.md",
  },
  {
    id: "message-bubble",
    title: "Message Bubble",
    description: "Chat message component with spring pop-in entry and typing indicator.",
    category: "Feedback",
    span: "2x2",
    status: "live",
    tags: ["Chat", "Message", "Bubble", "Typing"],
    docPath: "docs/MESSAGE_BUBBLE.md",
  },
  {
    id: "notification-stack",
    title: "Notification Stack",
    description: "Floating banner stack with expansion collapse preview on hover.",
    category: "Feedback",
    span: "2x2",
    status: "live",
    tags: ["Notification", "Banner", "Stack", "Alert"],
    docPath: "docs/NOTIFICATION_STACK.md",
  },
  {
    id: "number-flow",
    title: "Number Flow",
    description: "Smooth rolling counter for numbers and financial metrics change transitions.",
    category: "Motion",
    span: "1x1",
    status: "live",
    tags: ["Counter", "Number", "Flow", "Animation"],
    docPath: "docs/NUMBER_FLOW.md",
  },

  {
    id: "pop-over",
    title: "Pop Over",
    description: "Positioned popover card trigger with subtle arrow indicator and spring scale.",
    category: "Navigation",
    span: "2x1",
    status: "live",
    tags: ["Popover", "Tooltip", "Dropdown", "Overlay"],
    docPath: "docs/POP_OVER.md",
  },
  {
    id: "portfolio-allocation",
    title: "Portfolio Allocation",
    description: "Asset distribution visualizer with interactive segment highlights and percentage breakdown.",
    category: "Data",
    span: "2x2",
    status: "live",
    tags: ["Portfolio", "Finance", "Chart", "Allocation"],
    docPath: "docs/PORTFOLIO_ALLOCATION.md",
  },
  {
    id: "preview-rail",
    title: "Preview Rail",
    description: "Horizontal image preview rail with smooth scale thumbnail magnification.",
    category: "Navigation",
    span: "2x1",
    status: "live",
    tags: ["Rail", "Carousel", "Thumbnails", "Preview"],
    docPath: "docs/PREVIEW_RAIL.md",
  },
  {
    id: "range-slider",
    title: "Custom Range Slider",
    description: "Dual-thumb or single-thumb slider with custom track fill and tooltip value indicator.",
    category: "Inputs",
    span: "2x1",
    status: "live",
    tags: ["Slider", "Range", "Input", "Control"],
    docPath: "docs/RANGE_SLIDER.md",
  },
  {
    id: "select-dropdown",
    title: "Select Dropdown",
    description: "Custom styled dropdown select menu with checkmark states and smooth spring open.",
    category: "Inputs",
    span: "2x1",
    status: "live",
    tags: ["Select", "Dropdown", "Form", "Menu"],
    docPath: "docs/SELECT_DROPDOWN.md",
  },
  {
    id: "switch",
    title: "Animated Switch",
    description: "Toggle switch with smooth sliding thumb spring motion and icons.",
    category: "Inputs",
    span: "1x1",
    status: "live",
    tags: ["Switch", "Toggle", "Input", "Boolean"],
    docPath: "docs/SWITCH.md",
  },
  {
    id: "tabs",
    title: "Animated Tabs",
    description: "Tab bar with active background pill layout transition using Framer Motion layoutId.",
    category: "Navigation",
    span: "2x1",
    status: "live",
    tags: ["Tabs", "Pill", "Active Indicator", "Navigation"],
    docPath: "docs/TABS.md",
  },
  {
    id: "wheel-picker-date",
    title: "Wheel Picker Date",
    description: "iOS style 3D rotating wheel picker for dates, times, and numbers.",
    category: "Inputs",
    span: "2x2",
    status: "live",
    tags: ["Wheel Picker", "Date Picker", "iOS Style", "Scroll"],
    docPath: "docs/WHEEL_PICKER_DATE.md",
  },
];
